### ISSUE TITLE
Опубликовать релиз 1.1.1 для 1commands, а 1.1 удалить из хаба

### ISSUE THREAD

**Issue by artbear** [oscript-library/library-support#11]
https://github.com/artbear/1commands/releases/tag/1.1.1

Файл пакета для публикации https://github.com/artbear/1commands/files/811955/1commands-1.1.1.zip

@nixel2007 Сможешь опубликовать новый релиз, а 1.1 удалить из хаба?

**Comment by nixel2007** [comment]
done
