### ISSUE TITLE
Проверить публикацию пакетов после изменения версии пакета в ветке мастер

### ISSUE THREAD

**Issue by artbear** [oscript-library/library-support#5]
Только что выпустил версию 0.7 v8runner (PR + packadef изменил)
Нужно проверить автопаблиш этой версии.

**Comment by artbear** [comment]
Также выпустил версию 1.0 1commands.
И ее проверить.

**Comment by artbear** [comment]
Также тул1сд 0.3

**Comment by artbear** [comment]
И гитсинк 2.0

Я молодец :)

**Comment by nixel2007** [comment]
Крон не отработал. толкнул руками.

**Comment by nixel2007** [comment]
Настроил запуск по крону
