### ISSUE TITLE
Не опубликован релиз vanessa-runner v0.6.0

### ISSUE THREAD

**Issue by artbear** [oscript-library/library-support#9]
Есть релиз на гитхабе и в мастере https://github.com/silverbulleters/vanessa-runner/releases/tag/v0.6.0
но на хабе оскрипт.ио лежит версия 0.5.1 :(

@nixel2007 Сможешь вручную выложить? или другим способом исправить ошибку публикации?

сегодня нарвался у нашего общего клиента :(

**Comment by artbear** [comment]
![image](https://cloud.githubusercontent.com/assets/2920817/23407247/170c98d4-fdd4-11e6-9cd1-e6627cf20a3b.png)

**Comment by nixel2007** [comment]
Если соберешь ospx - выложу.

**Comment by artbear** [comment]
[vanessa-runner-0.6.0.zip](https://github.com/oscript-library/library-support/files/807414/vanessa-runner-0.6.0.zip)
Забирай архив с ospx

**Comment by nixel2007** [comment]
Не выкачивается. :(
Шли на почту.
